language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer self-update && composer install --dev --prefer-source --no-interaction

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
